platform :ios, '7.0'

pod 'pop'
pod 'ADTransitionController'
pod 'Masonry'
pod 'AFNetworking'
pod 'MBProgressHUD'
pod 'FMDB'
pod 'SDWebImage'
pod 'MJRefresh'

pod 'XMPPFramework'

pod 'ChameleonFramework'
pod 'Haneke', '~> 1.0'
pod 'SVProgressHUD'
pod 'TesseractOCRiOS', '4.0.0'